services:
  - type: web
    name: backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn.conf.py app:app"
    branch: main
    autoDeploy: true
    envVars:
      - key: RENDER
        value: true
    secrets:
      - name: firebase_credentials.json
        mountPath: /etc/secrets/